[#16] feat: mysql 컨테이너 compose에 포함

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -13,8 +13,6 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-        with:
-          ref: main # 배포는 항상 main 브랜치 기준으로 실행
 
       - name: Set up Java
         uses: actions/setup-java@v4
@@ -65,6 +63,18 @@ jobs:
           platforms: linux/amd64
           tags: ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
 
+      - name: Upload docker-compose.yml to Server
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USERNAME }}
+          password: ${{ secrets.SERVER_PASSWORD }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          source: "docker-compose-deploy.yml"
+          target: "~/app/"
+          overwrite: true
+          debug: true
+
       - name: Deploy to Server
         uses: appleboy/ssh-action@master
         with:
@@ -73,21 +83,26 @@ jobs:
           password: ${{ secrets.SERVER_PASSWORD }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
-            CONTAINER_NAME=gamchi-app
-            NETWORK_NAME=gamchi-network
-            
-            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_URL }}
-            docker pull ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
-            
-            if [ $(docker ps -a -q --filter "name=$CONTAINER_NAME") ]; then
-              docker stop $CONTAINER_NAME
-              docker rm $CONTAINER_NAME
+            DEPLOY_DIR=~/app
+            mkdir -p $DEPLOY_DIR
+            cd $DEPLOY_DIR
+
+            if [ ! -f docker-compose-deploy.yml ]; then
+              echo "ERROR: docker-compose-deploy.yml does not exist in $DEPLOY_DIR"
+              exit 1
+            else
+              echo "Found docker-compose-deploy.yml, renaming to docker-compose.yml"
+              mv docker-compose-deploy.yml docker-compose.yml
             fi
-            
-            docker run -d \
-              --name $CONTAINER_NAME \
-              --network $NETWORK_NAME \
-              -p 8080:8080 \
-              ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
-            
+
+            echo "IMAGE_TAG=${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}" > .env
+            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
+            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
+
+            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_URL }}
+
+            docker compose pull app
+
+            docker compose up -d
+
             docker image prune -a -f
